### ISSUE TITLE
Buffering issue

### ISSUE THREAD

**Issue by Hamzakhalid8595** [cuynu/archive#9]
Watch any video after some seconds or may be in one minute starts buffer and then can't play just buffering

**Comment by gauravraj018** [comment]
Yes same thing happening with me also I tried all solution from all posts not working

**Comment by Escanor12312** [comment]
yep I m facing the same buffering issue , i downloaded the previous version even that has Started buffering ,

**Comment by gauravraj018** [comment]
It solved for me download latest black version
17.33.42 black

**Comment by Hamzakhalid8595** [comment]
Ok 👍 i itry .thanks

**Comment by Escanor12312** [comment]
> It solved for me download latest black version 17.33.42 black

i did the same it worked for 1 day but starting next day I was facing the buffering issue again

**Comment by gauravraj018** [comment]
Same it was not working I just now downloaded 

> `Revanced Extended`

.Working smooth with no issue.

**Comment by Hamzakhalid8595** [comment]
Which version of black ?..because 17..... is not playing all videos

**Comment by Hamzakhalid8595** [comment]
Yes its solved.. thanks dear

**Comment by Kajimuno** [comment]
I tried downloading 17.32.42 yet to no avail it happens again it the videos only last 1 minute before it buffers again

**Comment by Kajimuno** [comment]
I might have to use that godforsaken stock youtube app again...

**Comment by cuynu** [comment]
this not a repo for report issues
